# Generated by Django 2.1.5 on 2019-03-02 18:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Cevap ID')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Cevabınız')),
                ('answerDate', models.DateTimeField(auto_now_add=True, verbose_name='Cevap Tarih')),
                ('bestAnswer', models.BooleanField(default=0, verbose_name='En Iyi Cevap')),
            ],
            options={
                'ordering': ['-answerDate'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteQuestionModel',
            fields=[
                ('favoriteQuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategoryModel',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False, verbose_name='Kategori ID')),
                ('categoryName', models.CharField(max_length=150, verbose_name='Kategori Adi')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Soru ID')),
                ('questionTitle', models.CharField(max_length=150, verbose_name='Soru Başlığı')),
                ('questionContent', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sorunuz')),
                ('questionCreateDate', models.DateTimeField(auto_now_add=True, verbose_name='Soru Olusturma Tarihi')),
                ('questionEditDate', models.DateTimeField(null=True, verbose_name='Soru Guncellenme Tarihi')),
                ('questionViewCounter', models.IntegerField(default=0, verbose_name='Okunma Sayisi')),
                ('slug', models.SlugField(editable=False, max_length=135, unique=True)),
                ('emailNotifications', models.BooleanField(default=True, verbose_name='Soruya cevap gelirse mail gönderilsin mi?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionReportModel',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False, verbose_name='Rapor ID')),
                ('reportReason', models.CharField(max_length=255, verbose_name='Raporlama Sebebi')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.QuestionModel')),
            ],
        ),
    ]
