# Generated by Django 2.1.5 on 2019-04-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20190302_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answermodel',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='vote_score',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='vote_score',
        ),
    ]
