# Generated by Django 2.1.5 on 2019-04-04 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0002_auto_20190302_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_status', models.SmallIntegerField(default=0, null=True, verbose_name='Score durumu')),
            ],
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='vote_score',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='vote_score',
        ),
        migrations.AddField(
            model_name='answermodel',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
        migrations.AddField(
            model_name='scoremodel',
            name='answer',
            field=models.ForeignKey(on_delete=True, related_name='score_answer', to='question.AnswerModel'),
        ),
        migrations.AddField(
            model_name='scoremodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=True, related_name='score_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
