# Generated by Django 2.1.5 on 2019-04-04 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0003_auto_20190404_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_status', models.SmallIntegerField(default=0, null=True, verbose_name='Score durumu')),
                ('answer', models.ForeignKey(on_delete=True, related_name='score_answer', to='question.AnswerModel')),
                ('user', models.ForeignKey(null=True, on_delete=True, related_name='score_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
